Think I have set up the jobs correctly in the workflows

diff --git a/.github/workflows/python-codecov-ci.yml b/.github/workflows/python-codecov-ci.yml
--- a/.github/workflows/python-codecov-ci.yml
+++ b/.github/workflows/python-codecov-ci.yml
@@ -2,9 +2,9 @@ name: API workflow
 
 on: [push, pull_request]
 
-      # ---------------------------------------------------------
-      # CREATE THE EVENT FILE
-      # ---------------------------------------------------------
+  # ---------------------------------------------------------
+  # CREATE THE EVENT FILE
+  # ---------------------------------------------------------
 
 jobs:
   event_file:
@@ -16,33 +16,54 @@ jobs:
         name: Event File
         path: ${{ github.event_path }}
 
-  setup:
+  # ---------------------------------------------------------
+  # JOB: CHECK DEPENDENCIES
+  # ---------------------------------------------------------
+  Dependencies:
+    name: Build env
     runs-on: ubuntu-latest
-    name: Test python API
-    steps:
+    steps: 
     - uses: actions/checkout@v4
     - uses: actions/setup-python@v2
       with:
         python-version: '3.10'    
-    - uses: codecov/codecov-action@v5
-      # ---------------------------------------------------------
-      # INSTALL DEPENDENCIES
-      # ---------------------------------------------------------
+
+    # ---------------------------------------------------------
+    # INSTALL DEPENDENCIES
+    # ---------------------------------------------------------
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         pip install -r requirements-dev.txt
 
-      # ---------------------------------------------------------
-      # RUN TESTS (FAILURE RECORDED, PIPELINE CONTINUES)
-      # ---------------------------------------------------------
+  # ---------------------------------------------------------
+  # SETUP FOR JOB: TEST
+  # ---------------------------------------------------------
   Test:
     name: Run tests
-    needs: setup
+    needs: event_file
     runs-on: ubuntu-latest
-    steps:
+    steps: 
     - uses: actions/checkout@v4
+    - uses: actions/setup-python@v2
+      with:
+        python-version: '3.10'    
+
+    # ---------------------------------------------------------
+    # INSTALL DEPENDENCIES
+    # ---------------------------------------------------------
+
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install -r requirements.txt
+        pip install -r requirements-dev.txt
+    # ---------------------------------------------------------
+    # RUN TESTS
+    # ---------------------------------------------------------
+
     - name: Run pytest
       run: |
         mkdir -p test-results
@@ -51,32 +72,47 @@ jobs:
       # ---------------------------------------------------------
       # UPLOAD TEST RESULTS
       # ---------------------------------------------------------
-  Upload_test_results:
-    name: Upload Test Results
-    needs: Test
-    runs-on: ubuntu-latest
-    if: always()
-    steps:
-    - uses: actions/upload-artifact@v4
+    - name: Upload Test Results
+      if: always()
+      uses: actions/upload-artifact@v4
       with:
         name: Test Results
         path: test-results/*.xml
 
-      # ---------------------------------------------------------
-      # UPLOAD COVERAGE TO CODECOV
-      # ---------------------------------------------------------
+  # ---------------------------------------------------------
+  # SETUP FOR JOB: CODECOV
+  # ---------------------------------------------------------
   Codecov:
     name: Setup Codecov
-    needs: setup
+    needs: Dependencies
     runs-on: ubuntu-latest
     if: always()
-    steps:
+    steps: 
     - uses: actions/checkout@v4
-    - name: Create coverage report
-      if: always()
+    - uses: actions/setup-python@v2
+      with:
+        python-version: '3.10'    
+
+    # ---------------------------------------------------------
+    # INSTALL DEPENDENCIES
+    # ---------------------------------------------------------
+
+    - name: Install dependencies
       run: |
-          pytest --cov . \
-            --cov-report=xml:test-results/coverage.xml
+        python -m pip install --upgrade pip
+        pip install -r requirements.txt
+        pip install -r requirements-dev.txt
+      # ---------------------------------------------------------
+      # RUN TESTS AND CREATE REPORT
+      # ---------------------------------------------------------
+    - name: Run Tests
+      run: |
+        mkdir -p test-results
+        pytest --cov . --junitxml=test-results/results.xml --cov-report=xml:test-results/coverage-service.xml
+
+      # ---------------------------------------------------------
+      # UPLOAD TEST RESULTS TO CODECOV
+      # ---------------------------------------------------------
     - name: Upload coverage reports to Codecov
       if: always()
       run: |
@@ -87,40 +123,73 @@ jobs:
        -t "${{ secrets.CODECOV_TOKEN }}" \
        -n "service-${{ github.run_id }}" \
        -F service \
-       -f coverage-service.xml
+       -f test-results/coverage-service.xml
 
-      # ---------------------------------------------------------
-      # FORMAT CODE WITH BLACK
-      # Ref: https://towardsdatascience.com/black-with-git-hub-actions
-      # ---------------------------------------------------------
+  # ---------------------------------------------------------
+  # JOB: FORMAT CODE WITH BLACK
+  # Ref: https://towardsdatascience.com/black-with-git-hub-actions
+  # ---------------------------------------------------------
   Black:
     name: Format_code_with_black
-    needs: setup
+    needs: Dependencies
     runs-on: ubuntu-latest
     if: always()
-    steps:
+    steps: 
+    - uses: actions/checkout@v4
+    - uses: actions/setup-python@v2
+      with:
+        python-version: '3.10'    
+
+    # ---------------------------------------------------------
+    # INSTALL DEPENDENCIES
+    # ---------------------------------------------------------
+
+    - name: Install Black
+      run: |
+        python -m pip install --upgrade pip
+        pip install black
+
+    # ---------------------------------------------------------
+    # FORMAT WITH BLACK
+    # ---------------------------------------------------------
     - name: Format
       run: |
         black .
-      # ---------------------------------------------------------
-      # LINTING 
-      # ---------------------------------------------------------
+  # ---------------------------------------------------------
+  # LINTING 
+  # ---------------------------------------------------------
   Flake8:
     name: Run_Flake8
-    needs: setup
+    needs: Black
     runs-on: ubuntu-latest
-    if: always()
-    steps:
+    steps: 
+    - uses: actions/checkout@v4
+    - uses: actions/setup-python@v2
+      with:
+        python-version: '3.10'    
+
+    # ---------------------------------------------------------
+    # INSTALL DEPENDENCIES
+    # ---------------------------------------------------------
+
+    - name: Install Flake8
+      run: |
+        python -m pip install --upgrade pip
+        pip install flake8
+    # ---------------------------------------------------------
+    # LINT WITH FLAKE 8
+    # ---------------------------------------------------------
     - name: Lint
       run: |
-        set +e
-        flake8 .
-        EXIT_CODE=$?
-        set -e
-
-        if [ $EXIT_CODE -ne 0 ]; then
-        echo "LINT_FAILED=true" >> $GITHUB_ENV
+        LINT_OUTPUT=$(flake8 .)
+        echo "$LINT_OUTPUT"
+        if [ -n "$LINT_OUTPUT" ]; then
+          echo "Linting failed!"
+          exit 1
         fi
+      # Run flake8 and capture output
+      # Fail the job if Lint Output is non-empty
+
       # ---------------------------------------------------------
       # MOVING ONTO TEST REPORT PUBLICATION
       # ---------------------------------------------------------
